In [2]:
import numpy as np

In [2]:
data = np.random.randn(2, 3)
data * 10

array([[ 14.50389107,   6.6270449 ,   1.41191882],
       [  9.4285713 , -20.35262892, -15.55678788]])

In [3]:
data.shape

(2, 3)

In [11]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.ndarray(data1, dtype = np.float64)
#arr1 = np.array(data1)
arr1

/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:2: VisibleDeprecationWarning: using a non-integer number instead of an integer will result in an error in the future
  from ipykernel import kernelapp as app


array([], shape=(6, 7, 8, 0, 1), dtype=float64)

In [12]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
arr[5]

5

In [14]:
arr[5:8]

array([5, 6, 7])

In [16]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [17]:
arr[1:6]

array([ 1,  2,  3,  4, 12])

In [18]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d[0]

array([1, 2, 3])

In [19]:
arr2d[0][2]

3

In [20]:
arr2d[0, 2]

3

In [23]:
print arr2d[:2]

[[1 2 3]
 [4 5 6]]


In [24]:
print arr2d[:2, 1:]

[[2 3]
 [5 6]]


In [25]:
print arr2d[1, :2]

[4 5]


In [26]:
arr2d[:2, :1] = 0
arr2d

array([[0, 2, 3],
       [0, 5, 6],
       [7, 8, 9]])

In [27]:
x = np.array([1, 4, 10])
x
x.dtype

dtype('int64')

In [28]:
y = x.astype(np.float64)
y.dtype

dtype('float64')

In [29]:
names = np.array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'])
data = np.random.rand(7, 4) # 표준 정규 분포 데이터

In [33]:
data

array([[  2.08092480e-01,   5.46192488e-02,   7.47413084e-01,
          8.81246437e-01],
       [  7.31357974e-04,   3.63405161e-01,   1.10442049e-02,
          9.57993480e-01],
       [  2.02966568e-02,   1.56718623e-01,   3.26689567e-01,
          3.07679685e-01],
       [  6.55926106e-01,   8.79662713e-01,   8.40567298e-02,
          2.57234330e-01],
       [  6.91009811e-01,   2.83423725e-01,   3.32790367e-01,
          2.12484056e-01],
       [  1.37680711e-01,   8.91186251e-02,   5.56065823e-01,
          6.29971117e-01],
       [  5.28358224e-01,   6.21979854e-01,   8.81519846e-01,
          3.43594751e-01]])

In [37]:
data[, 2:]

/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:1: VisibleDeprecationWarning: using a boolean instead of an integer will result in an error in the future
  if __name__ == '__main__':


array([ 0.0110442 ,  0.95799348])

In [30]:
print names == 'bob'

[ True False False  True False False False]


In [31]:
print data[names == 'bob']

[[ 0.20809248  0.05461925  0.74741308  0.88124644]
 [ 0.65592611  0.87966271  0.08405673  0.25723433]]


In [32]:
print data[names == 'bob', 2:]

[[ 0.74741308  0.88124644]
 [ 0.08405673  0.25723433]]


In [34]:
print names != 'bob'

[False  True  True False  True  True  True]


In [40]:
print logical_not(name == 'bob')

NameError: name 'logical_not' is not defined

In [38]:
mask = (names == 'bob') | (names == 'will')
mask

array([ True, False,  True,  True,  True, False, False], dtype=bool)

In [39]:
print data[mask]

[[ 0.20809248  0.05461925  0.74741308  0.88124644]
 [ 0.02029666  0.15671862  0.32668957  0.30767968]
 [ 0.65592611  0.87966271  0.08405673  0.25723433]
 [ 0.69100981  0.28342373  0.33279037  0.21248406]]


In [41]:
arr = np.empty((8, 4))
arr

array([[  6.91603142e-310,   2.24966982e-316,   0.00000000e+000,
          0.00000000e+000],
       [  1.90979621e-313,   2.14027814e+161,   5.04621383e+180,
          4.50618615e-144],
       [  7.79952704e-143,   4.50605602e-144,   4.27255699e+180,
          2.91237123e+257],
       [  5.56111702e+180,   2.16385138e+190,   7.42802406e+020,
          4.84034312e+015],
       [  1.58546122e+006,   6.12678243e-062,   4.27771322e-096,
          9.08366793e+223],
       [  1.14133876e+016,   5.80632736e-057,   1.57185333e-066,
          2.42790425e-052],
       [  1.41529402e+161,   9.16651763e-072,   4.95463598e+097,
          2.90378581e-057],
       [  6.15793652e-144,   1.25197768e-312,   0.00000000e+000,
          3.06320700e-322]])

In [42]:
for i in range(8):
    arr[i] = i
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [54]:
#arr[[4, 3, 7, 6]]
arr[0,3]

0.0

In [44]:
arr[[-3, -5, -7]]

array([[ 5.,  5.,  5.,  5.],
       [ 3.,  3.,  3.,  3.],
       [ 1.,  1.,  1.,  1.]])

In [60]:
arr = np.arange(32).reshape((8, 4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [115]:
arr[:3]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [130]:
arr[[1, 5, 7, 2]][:6]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [76]:
arr[[1, 5, 7, 2]] [:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [111]:
arr[[1, 5, 7, 2]][[0, 1, 2, 3]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [113]:
# arr의 1행, 5행, 7행, 2행을 
arr[[1, 5, 7, 2]][[0, 3, 1, 2]]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [20, 21, 22, 23],
       [28, 29, 30, 31]])

In [88]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [65]:
arr[:, [0, 3, 1, 2]]

array([[ 0,  3,  1,  2],
       [ 4,  7,  5,  6],
       [ 8, 11,  9, 10],
       [12, 15, 13, 14],
       [16, 19, 17, 18],
       [20, 23, 21, 22],
       [24, 27, 25, 26],
       [28, 31, 29, 30]])

In [146]:
ar = []

In [131]:
data2 = [[0, 1, 2, 3, 4, 5], [10, 11, 12, 13, 14, 15], [20, 21, 22, 23, 24, 25],
        [30, 31, 32, 33, 34, 35], [40, 41, 42, 43, 44, 45], [50, 51 ,52, 53, 54, 55]]
arr2 = np.array(data2)
arr2

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [132]:
arr2[[0, 0, 1, 2, 2, 3, 4, 5], [1, 2, 2, 2, 3, 4, 5, 2]]

array([ 1,  2, 12, 22, 23, 34, 45, 52])

In [145]:
arr2[[3, 4, 5]][:, [0, 2, 5]]

array([[30, 32, 35],
       [40, 42, 45],
       [50, 52, 55]])

In [174]:
arr2[[3, 4, 5]][0, 2]

32

In [194]:
arr = []
#ad = []

In [195]:
for i in range(6):
    ad = []
    for j in range(6):
        ad.append(i * 10 + j)
    arr.append(ad)

In [196]:
arr

[[0, 1, 2, 3, 4, 5],
 [10, 11, 12, 13, 14, 15],
 [20, 21, 22, 23, 24, 25],
 [30, 31, 32, 33, 34, 35],
 [40, 41, 42, 43, 44, 45],
 [50, 51, 52, 53, 54, 55]]

In [197]:
arr = np.array(arr)

In [198]:
print arr[[0, 1, 2, 3, 4], [1, 2, 3, 4, 5]]

[ 1 12 23 34 45]


In [199]:
mask = np.array([1, 0, 1, 0, 0, 1], dtype = bool)
arr[mask, 2]

array([ 2, 22, 52])

In [203]:
arr[[3, 4, 5]][:, [0, 2, 5]]

array([[30, 32, 35],
       [40, 42, 45],
       [50, 52, 55]])

# 전치 행렬 계산

In [206]:
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [207]:
arr = arr.reshape((3, 5))
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [208]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [209]:
arr1 = np.random.randn(6, 3)
arr1

array([[-1.31742456, -0.50903382,  2.08032052],
       [-0.03146548, -0.00769815, -0.20250048],
       [-0.7527987 ,  0.05366898, -1.19843269],
       [ 1.93457705,  0.57553653, -1.48905271],
       [ 1.69462567, -1.0057431 , -0.03088412],
       [-0.47289516, -0.09607096,  1.04636978]])

In [210]:
np.dot(arr.T, arr)

array([[125, 140, 155, 170, 185],
       [140, 158, 176, 194, 212],
       [155, 176, 197, 218, 239],
       [170, 194, 218, 242, 266],
       [185, 212, 239, 266, 293]])

In [215]:
arr.dot(arr.T)

array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [217]:
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
arr3 * arr3

array([[ 1,  4,  9],
       [16, 25, 36]])

In [218]:
arr3 - arr3

array([[0, 0, 0],
       [0, 0, 0]])

In [220]:
1. / arr3

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [222]:
arr3 ** 0.5

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

In [223]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [224]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [225]:
old_values = arr3d.copy()
arr3d[0] = 42

In [226]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [247]:
arr3d[1][:, [0]]

array([[ 7],
       [10]])

# 내적의 의미

In [249]:
# 100원짜리 제품 1개, ... 500원짜리 제품 5개일 때 총 매출은? (내적으로 구할 수 있다)
arr = np.array([100, 200, 300, 400, 500])
count = np.array([1, 2, 3, 4, 5])
np.dot(arr, count)

5500

In [251]:
sum(arr * count)

5500

# 단항함수

In [252]:
arr = np.arange(10)
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ])

In [253]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03])

In [257]:
x = np.random.randn(8)
y = np.random.randn(8)
print x, '\n', y

[-1.02304712 -0.51899505 -1.5499076  -0.78991836 -0.21480632  0.0818065
 -0.90699717 -0.03415713] 
[ 0.03409342 -0.20494572 -1.80742664 -2.22338727 -1.01296105 -0.14583648
  0.27249335  0.53058457]


In [258]:
np.maximum(x, y)

array([ 0.03409342, -0.20494572, -1.5499076 , -0.78991836, -0.21480632,
        0.0818065 ,  0.27249335,  0.53058457])

In [260]:
arr = np.random.randn(7) * 5
np.modf(arr)

(array([ 0.59240338,  0.00291057, -0.29847889, -0.08680564,  0.86084317,
         0.62656222, -0.06707851]),
 array([  1.,   4.,  -2.,  -5.,   5.,  12., -15.]))

# where (조건에 따른 출력값 조정)

In [269]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5])
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5])
cond = np.array([True, False, True, True, False])
result = [(x if c else y) for x, y, c in zip(xarr, yarr, cond)]
np.round(result, 2)

array([ 1.1,  2.2,  1.3,  1.4,  2.5])

In [270]:
np.where(cond, xarr, yarr)

array([ 1.1,  2.2,  1.3,  1.4,  2.5])

In [273]:
arr = np.random.randn(4, 4)
np.where(arr > 0, 2, -2)

array([[ 2,  2,  2, -2],
       [-2,  2, -2, -2],
       [ 2,  2,  2,  2],
       [ 2, -2,  2, -2]])

In [272]:
np.where(arr > 0, 2, arr)

array([[-1.02414178,  2.        ,  2.        , -0.16621736],
       [-0.93569335, -0.18241862, -0.02667998,  2.        ],
       [ 2.        , -1.63168405, -0.87189038,  2.        ],
       [-0.62961481,  2.        , -1.45217304,  2.        ]])

In [279]:
result = []
cond1 = np.array([1, 0, 1, 1, 0, 0, 1], dtype = bool)
cond2 = np.array([0, 1, 1, 1, 0, 1, 1], dtype = bool)
n = 7

In [282]:
for i in range(n):
    if(cond1[i] and cond2[i]):
        result.append(0)
    elif cond1[i]:
        result.append(1)
    elif cond2[i]:
        result.append(2)
    else:
        result.append(3)

In [283]:
result

[1, 2, 0, 0, 3, 2, 0]

In [284]:
np.where(cond1 & cond2, 0, np.where(cond1, 1, np.where(cond2, 2, 3)))

array([1, 2, 0, 0, 3, 2, 0])

In [292]:
1 * (cond1 & ~cond2) + 2 * (~cond1 & cond2) + 3 * (~cond1 & ~cond2)

array([1, 2, 0, 0, 3, 2, 0])

In [293]:
1 * (cond1 & ~cond2) + 2 * (~cond1 & cond2) + 3 * ~(cond1 | cond2)

array([1, 2, 0, 0, 3, 2, 0])

# cumsum, cumprod

In [294]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [301]:
arr.cumsum(axis = 0)

array([[ 1,  2,  3],
       [ 5,  7,  9],
       [12, 15, 18]])

In [300]:
arr.cumprod(axis = 0)

array([[  1,   2,   3],
       [  4,  10,  18],
       [ 28,  80, 162]])

In [302]:
arr = np.random.randn(5, 4)
arr

array([[ 0.70067514, -0.22751786,  0.82701477,  0.85480517],
       [-0.56176607,  0.05448278,  0.5418823 , -1.48392215],
       [ 1.36285387,  1.11343109,  0.35673243, -0.45075803],
       [ 1.71379945, -1.33337064, -0.24769023, -1.07424148],
       [-0.26234045,  0.13809224,  2.10848844,  0.08702037]])

In [303]:
arr.mean()

0.21088355653847218

In [304]:
np.mean(arr)

0.21088355653847218

In [305]:
arr.mean(axis = 1)

array([ 0.5387443 , -0.36233079,  0.59556484, -0.23537573,  0.51781515])

In [306]:
arr.mean(axis = 0)

array([ 0.59064439, -0.05097648,  0.71728554, -0.41341922])

In [307]:
arr.sum(axis = 0)

array([ 2.95322193, -0.25488239,  3.58642771, -2.06709612])

In [310]:
arr = np.random.randn(8)
arr.sort()
arr

array([-2.09618305, -1.72583703, -0.9609046 , -0.69740971, -0.6747691 ,
        0.14268608,  0.44493463,  1.18373539])

In [312]:
arr = np.random.randn(5, 3)
arr

array([[-0.52422256,  0.21852438, -1.88260691],
       [-0.02328303,  0.77656649,  1.17618877],
       [-0.81659209,  2.43345439, -0.18139049],
       [ 0.13517775, -1.08548762,  1.6055451 ],
       [ 0.34763   ,  1.15561343, -1.41018545]])

In [313]:
arr.sort(1)
arr

array([[-1.88260691, -0.52422256,  0.21852438],
       [-0.02328303,  0.77656649,  1.17618877],
       [-0.81659209, -0.18139049,  2.43345439],
       [-1.08548762,  0.13517775,  1.6055451 ],
       [-1.41018545,  0.34763   ,  1.15561343]])

In [327]:
arr[::-1]

array([[-1.41018545,  0.34763   ,  1.15561343],
       [-1.08548762,  0.13517775,  1.6055451 ],
       [-0.81659209, -0.18139049,  2.43345439],
       [-0.02328303,  0.77656649,  1.17618877],
       [-1.88260691, -0.52422256,  0.21852438]])

In [314]:
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05 * len(large_arr))]

-1.5639958706119206

In [317]:
large_arr[len(large_arr) - 1]

3.3516596884543413

In [331]:
a = np.array([[1, 4], [3, 1]])
#np.sort(a)
a

array([[1, 4],
       [3, 1]])

In [329]:
np.sort(a, axis = None)

array([1, 1, 3, 4])

In [330]:
np.sort(a, axis = 0)

array([[1, 1],
       [3, 4]])

In [335]:
del a

In [342]:
dtype = [('name', 'S10'), ('height', float), ('age', int)]
values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38), ('Galahad', 1.7, 38)]
a = np.array(values, dtype = dtype)
print a

[('Arthur', 1.8, 41) ('Lancelot', 1.9, 38) ('Galahad', 1.7, 38)]


In [344]:
np.sort(a, order = 'height')
print a

[('Arthur', 1.8, 41) ('Lancelot', 1.9, 38) ('Galahad', 1.7, 38)]


In [346]:
np.sort(a, order = ['age', 'height'])

array([('Galahad', 1.7, 38), ('Lancelot', 1.9, 38), ('Arthur', 1.8, 41)], 
      dtype=[('name', 'S10'), ('height', '<f8'), ('age', '<i8')])